web:
  build: .
  command: python -u app/app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/todo
  links:
    - db
db:
  image: mongo:4.0.2
  environment:
  - MONGO_DATA_DIR=/data/db
  - MONGO_LOG_DIR=/dev/null
  ports:
    - "27020:27020"
  volumes:
    - ./data/db:/data/db
  command: mongod --port 27020 --smallfiles --logpath=/dev/null # --quiet
